#lang sicp
;Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.
; (define (dec x) (- x 1))
; (define (inc x) (+ x 1))
; (define (add a b)
;   (if (= a 0) 
;       b 
;       (inc (add (dec a) b))))

; (define (add a b)
;   (if (= a 0) 
;       b 
;       (add (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each procedure in evaluating (add 4 5). Are these processes iterative or recursive? 
; **ANSWER **
; First definition:
; (add 4 5)
; (inc (add (dec 4) 5))
; (inc (inc (add (dec 3) 5)))
; (inc (inc (inc (add (dec 2) 5))))
; (inc (inc (inc (inc (add (dec 1) 5)))))
; (inc (inc (inc (inc (add 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9
; This is a linear recursive process, as indicated by the expansion
; and contraction behavior

; Second definition:
; (add 4 5)
; (add (dec 4) (inc 5))
; (add 3 6)
; (add (dec 3) (inc 6))
; (add 2 7)
; (add (dec 2) (inc 7))
; (add 1 8)
; (add (dec 1) (inc 8))
; (add 0 9)
; 9
; This one is linear iterative, as the calculations are kept track of
; by state variables, and calculations are not deferred

; Exercise 1.10: The following procedure computes a mathematical function called Ackermann’s function.

; (define (A x y)
;   (cond ((= y 0) 0)
;         ((= x 0) (* 2 y))
;         ((= y 1) 2)
;         (else (A (- x 1)
;                  (A x (- y 1))))))

; What are the values of the following expressions?

; (A 1 10) ; 1024
; (A 2 4) ; 65536
; (A 3 3) ; 65536

; Consider the following procedures, where A is the procedure defined above:

; (define (f n) (A 0 n))
; (define (g n) (A 1 n))
; (define (h n) (A 2 n))
; (define (k n) (* 5 n n))

; Give concise mathematical definitions for the functions computed by the procedures f, g, and h for positive integer values of n . For example, (k n) computes 5n^2 . 
; ANSWER
; using substitution:
; (f n)
; (A 0 n)
; (* 2 n)
; so f(n) = 2n

; (g n)
; (A 1 n)

; (A (- 1 1)
;     (A 1 (- n 1)))

; (A 0
;     (A 1 (- n 1)))

; (* 2 (A 1 (- n 1)))

; (* 2 
;     (A (- 1 1)
;         (A 1 (- (- n 1) 1)))
; )

; (* 2 
;     (A 0
;         (A 1 (- (- n 1) 1)))
; )

; (* 2 
;     (* 2
;         (A 1 (- (- n 1) 1)))
; )

; (* 2 
;     (* 2
;         (* 2
;             (A 1 (- (- (- n 1) 1) 1))))
; )

; and so on
; suppose n = 4
; (* 2 
;     (* 2
;         (* 2
;             (A 1 1)))
; )

; (* 2 
;     (* 2
;         (* 2
;             2))
; )
; so it equals 2^4
; so, g(n) = 2^n

; (define n 3)
; (h n)
; (A 2 n)

; (A (- 2 1)
;     (A 2 (- n 1)))

; (A 1
;    (A 2 (- n 1)))

; (g (A 2 (- n 1)))

; (g (A (- 2 1)
;    (A 2 (- (- n 1) 1))))

; (g 
;   (g
;     (A 2 (- (- n 1) 1))))
; ; let n = 3

; (g 
;   (g
;     (A 2 1)))
; (g 
;   (g
;     2))
; = 2^2^2
; g(n) = 2^2 exponent done n times total
; g(n) = 2↑↑n

; Exercise 1.11: A function f is defined by the rule that f ( n ) = n if n < 3 and f ( n ) = f ( n − 1 ) + 2 f ( n − 2 ) + 3 f ( n − 3 ) if n ≥ 3 . Write a procedure that computes f by means of a recursive process. Write a procedure that computes f by means of an iterative process. 
; ** ANSWER ** 
; recursive process:
(define (f n) 
    (if (< n 3) 
        n 
        (+ (f (- n 1)) 
           (* 2 (f (- n 2))) 
           (* 3 (f (- n 3))) 
        )
    )
)

; iterative process:
; start with 3 state variables:
; a=2 b=1 c=0
; for n >=3
; a = a + 2*b + 3*c
; b = a
; c = b
; do this n times
; (define (new-a a b c) (+ a (* 2 b) (* 3 c)))
; (define (f-iter a b c count) 
;     (if (<= count 1) 
;         b 
;         (f-iter (new-a a b c) a b (- count 1) )))

; (define (f n) (if (< n 3) n (f-iter 2 1 0 n)))


; (f -1)
; (f 0)
; (f 1)
; (f 2)
; (f 3)
; (f 4)
; (f 5)

; Exercise 1.12: The following pattern of numbers is called Pascal’s triangle.

;          1
;        1   1
;      1   2   1 row=3 n = 2. above is row = 2, n=1,2 
;    1   3   3   1 row=4, n=2 above is n=1 and 2. for n=3, above is 2,3
;  1   4   6   4   1
;        . . .

; The numbers at the edge of the triangle are all 1, and each number inside the triangle is the sum of the two numbers above it.35 Write a procedure that computes elements of Pascal’s triangle by means of a recursive process.

; (define (compute-element row n) 
;     (cond
;         ((= n 1) 1)
;         ((= n row) 1)
;         (else (+ (compute-element (- row 1) (- n 1)) (compute-element (- row 1) n)) )
;     )
; )

; (compute-element 1 1)

; (compute-element 2 1)
; (compute-element 2 2)

; (compute-element 3 1)
; (compute-element 3 2)
; (compute-element 3 3)

; (compute-element 4 1)
; (compute-element 4 2)
; (compute-element 4 3)
; (compute-element 4 4)

; (compute-element 5 1)
; (compute-element 5 2)
; (compute-element 5 3)
; (compute-element 5 4)
; (compute-element 5 5)

; Exercise 1.14: Draw the tree illustrating the process generated by the count-change procedure of 1.2.2 in making change for 11 cents. What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases? 
; (define (count-change amount)
;   (cc amount 5))

; (define (cc amount kinds-of-coins)
;   (cond ((= amount 0) 1)
;         ((or (< amount 0) 
;              (= kinds-of-coins 0)) 
;          0)
;         (else 
;          (+ (cc amount (- kinds-of-coins 1))
;             (cc (- amount (first-denomination 
;                            kinds-of-coins))
;                 kinds-of-coins)))))

; (define (first-denomination kinds-of-coins)
;   (cond ((= kinds-of-coins 1) 1)
;         ((= kinds-of-coins 2) 5)
;         ((= kinds-of-coins 3) 10)
;         ((= kinds-of-coins 4) 25)
;         ((= kinds-of-coins 5) 50)))
; (cc 11 5)

; ANSWER
; Growth of Space:
; The growth of space of a tree-recursive process (like the cc function) is the depth. In this case,
; the depth is the case where the expression (cc (- amount (first-denomination kinds-of-coins)) is
; evaluated where (first-denomination 1) evaluates to 1, so the amount goes down by 1, amount times. 
; In other words, the growth of space is O(n) where n is amount.

; Growth of number of steps:
; The growth of the number of steps is proportional to the number of nodes in the tree.
; It grows exponentially with amount, or O(n) where n is amount.

; Exercise 1.15: The sine of an angle (specified in radians) can be computed by making use of the approximation sin ⁡ x ≈ x if x is sufficiently small, and the trigonometric identity
; sin ⁡ x = 3 sin ⁡ x 3 − 4 sin 3 ⁡ x 3
; to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered “sufficiently small” if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

;     How many times is the procedure p applied when (sine 12.15) is evaluated?
;     What is the order of growth in space and number of steps (as a function of a ) used by the process generated by the sine procedure when (sine a) is evaluated? 

; ANSWER
; (sine 12.15)
; (p (sine (/ 12.15 3)))
; (sin 4.05)
; (p (sine (/ 4.05 3)))
; (sin 1.35)
; (p (sine (/ 1.35 3)))
; (sin 0.45)
; (p (sine (/ 0.45 3)))
; (sin 0.15)
; (p (sine (/ 0.15 3)))
; (sin 0.05)

; By the above expansion, p is called 5 times.
; This is a linear recursive procedure, so the growth of both space and steps is O(n)

; Exercise 1.16: Design a procedure that evolves an iterative exponentiation process that uses successive squaring and uses a logarithmic number of steps, as does fast-expt. (Hint: Using the observation that ( b n / 2 ) 2 = ( b 2 ) n / 2 , keep, along with the exponent n and the base b , an additional state variable a , and define the state transformation in such a way that the product a b n is unchanged from state to state. At the beginning of the process a is taken to be 1, and the answer is given by the value of a at the end of the process. In general, the technique of defining an invariant quantity that remains unchanged from state to state is a powerful way to think about the design of iterative algorithms.) 
; the invariant quantity is a*b^n

; (define (even? n)
;   (= (remainder n 2) 0))

; (define (fast-expt b n)
;     (expt-iter b n 1))

; (define (expt-iter b n a)
;       (cond 
;         ((= n 0) a)
;         ((even? n) 
;          (expt-iter (* b b) (/ n 2) a)
;         )
;         (else
;          (expt-iter b (- n 1) (* a b)))
;        )
; )

; (fast-expt 2 3)   ; expect 8
; (fast-expt 2 2)   ; expect 4
; (fast-expt 1 3)   ; expect 1
; (fast-expt 2 10)  ; expect 1024
; (fast-expt 3 3)   ; expect 27
; (fast-expt 3 4)   ; expect 81
; (fast-expt 5 3)   ; expect 125
; (fast-expt 2 0)   ; expect 1
; (fast-expt 7 2)   ; expect 49
; (fast-expt 2 16)  ; expect 65536
; (fast-expt 3 5)   ; expect 243
; (fast-expt 10 4)  ; expect 10000
; (fast-expt 2 20)  ; expect 1048576


; Exercise 1.17: The exponentiation algorithms in this section are based on performing exponentiation by means of repeated multiplication. In a similar way, one can perform integer multiplication by means of repeated addition. The following multiplication procedure (in which it is assumed that our language can only add, not multiply) is analogous to the expt procedure:

; (define (* a b)
;   (if (= b 0)
;       0
;       (+ a (* a (- b 1)))))

; This algorithm takes a number of steps that is linear in b. Now suppose we include, together with addition, operations double, which doubles an integer, and halve, which divides an (even) integer by 2. Using these, design a multiplication procedure analogous to fast-expt that uses a logarithmic number of steps. 

(define (double n) (+ n n))
(define (halve n ) (/ n 2))

; In the example function written, it uses this property:
; a * b = a + a*(b-1)
; we want to use halve and double
; suppose both a and b > 1, and b is even
; a*b = (double a) * (halve b)
; now suppose b is odd, we use the previous identity
; base case is when b = 1, return a

; (define (* a b)
;     (cond 
;         ((= b 1) a)
;         ((odd? b) (+ a (* a (- b 1))))
;         (else (* (double a) (halve b)))
;     )
; )

; Exercise 1.18: Using the results of Exercise 1.16 and Exercise 1.17, devise a procedure that generates an iterative process for multiplying two integers in terms of adding, doubling, and halving and uses a logarithmic number of steps.
; like in exercise 1.16 we want to use a state variable that does not change value
; the transformation is the same as the previous example
; inavriant quantity is a * b + n
; so if b is odd we can do: a*(b-1) + (n+a)
; if b is even just: (double a)*(halve b) + n
; want to write procedure with tail recursion so it's iterative

; (define (* a b) (mult-iter a b 0))
; (define (mult-iter a b n)
;     (cond
;     ((= b 0) 0) ; need this for edge case
;     ((= b 1) (+ a n))
;     ((odd? b) (mult-iter a (- b 1) (+ n a)))
;     (else (mult-iter (double a) (halve b) n))
;     )
; )

; (* 2 3)     ; expect 6
; (* 1 1)     ; expect 1
; (* 10 10)   ; expect 100
; (* 5 1)     ; expect 5  (base case)
; (* 7 2)     ; expect 14 (even b)
; (* 7 3)     ; expect 21 (odd b)
; (* 0 5)     ; expect 0  (zero case — will this work?)
; (* 5 0)     ; expect 0  (zero case — will this work?)
; (* 1 100)   ; expect 100
; (* 2 16)    ; expect 32 (b is power of 2)
; (* 3 11)    ; expect 33 (odd b)
; (* 100 100) ; expect 10000

; Exercise 1.20: The process that a procedure generates is of course dependent on the rules used by the interpreter. As an example, consider the iterative gcd procedure given above. Suppose we were to interpret this procedure using normal-order evaluation, as discussed in 1.1.5. (The normal-order-evaluation rule for if is described in Exercise 1.5.) Using the substitution method (for normal order), illustrate the process generated in evaluating (gcd 206 40) and indicate the remainder operations that are actually performed. How many remainder operations are actually performed in the normal-order evaluation of (gcd 206 40)? In the applicative-order evaluation? 


; (define (gcd a b)
;   (if (= b 0)
;       a
;       (gcd b (remainder a b))))

; normal order case:
; (gcd 206 40)
; (if (= 40 0)
;       206
;       (gcd 40 (remainder 206 40)))
; (gcd 40 (remainder 206 40))
; (if (= 40 (remainder 206 40))
;       40
;       (gcd (remainder 206 40) (remainder 40 (remainder 206 40))))
; ; here remainder is evaluated according to the special form of if statements (#1)
; (gcd (remainder 206 40) (remainder 40 (remainder 206 40)))
;   (if (= (remainder 40 (remainder 206 40)) 0)
;       (remainder 206 40)
;       (gcd (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))))
; ; for the same reason as above remainder evalutes twice (count = 3)
; (gcd (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40))))
; (if (= (remainder (remainder 206 40) (remainder 40 (remainder 206 40))) 0)
;     (remainder 40 (remainder 206 40))
;     (gcd (remainder (remainder 206 40) (remainder 40 (remainder 206 40))) (remainder (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40))))))
; ; here in the if statement remainder evaluates 4 times (count = 7)

; (gcd (remainder (remainder 206 40) (remainder 40 (remainder 206 40))) (remainder (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))))
;   (if (= (remainder (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))) 0)
;       (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))
;       (gcd (remainder (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))) (remainder (remainder (remainder 206 40) (remainder 40 (remainder 206 40))) (remainder (remainder 40 (remainder 206 40)) (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))))))
; ; and another 7 times (total 14), where it fianlly equals 0 and we return a

; (remainder (remainder 206 40) (remainder 40 (remainder 206 40)))
; 14 + 4 = 18 total remainder operations

; applicative-order case:
(gcd 206 40)
(if (= 40 0)
      206
      (gcd 40 (remainder 206 40)))
; remainder count = 1
(gcd 40 6)
(if (= 6 0)
      40
      (gcd 6 (remainder 40 6)))
; count=2
(gcd 6 4)
(if (= 4 0)
      6
      (gcd 4 (remainder 6 4)))
; count = 3
(gcd 4 2)
(if (= 2 0)
      6
      (gcd 2 (remainder 4 2)))
; count = 4
(gcd 2 0)
(if (= 0 0)
      2
      (gcd 0 (remainder 2 0)))
2
; so in applicative-order evaluation remainder runs 4 times