#lang sicp
;Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.
; (define (dec x) (- x 1))
; (define (inc x) (+ x 1))
; (define (add a b)
;   (if (= a 0) 
;       b 
;       (inc (add (dec a) b))))

; (define (add a b)
;   (if (= a 0) 
;       b 
;       (add (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each procedure in evaluating (add 4 5). Are these processes iterative or recursive? 
; **ANSWER **
; First definition:
; (add 4 5)
; (inc (add (dec 4) 5))
; (inc (inc (add (dec 3) 5)))
; (inc (inc (inc (add (dec 2) 5))))
; (inc (inc (inc (inc (add (dec 1) 5)))))
; (inc (inc (inc (inc (add 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9
; This is a linear recursive process, as indicated by the expansion
; and contraction behavior

; Second definition:
; (add 4 5)
; (add (dec 4) (inc 5))
; (add 3 6)
; (add (dec 3) (inc 6))
; (add 2 7)
; (add (dec 2) (inc 7))
; (add 1 8)
; (add (dec 1) (inc 8))
; (add 0 9)
; 9
; This one is linear iterative, as the calculations are kept track of
; by state variables, and calculations are not deferred

; Exercise 1.10: The following procedure computes a mathematical function called Ackermann’s function.

(define (A x y)
  (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1)
                 (A x (- y 1))))))

; What are the values of the following expressions?

; (A 1 10) ; 1024
; (A 2 4) ; 65536
; (A 3 3) ; 65536

; Consider the following procedures, where A is the procedure defined above:

; (define (f n) (A 0 n))
(define (g n) (A 1 n))
(define (h n) (A 2 n))
; (define (k n) (* 5 n n))

; Give concise mathematical definitions for the functions computed by the procedures f, g, and h for positive integer values of n . For example, (k n) computes 5n^2 . 
; ANSWER
; using substitution:
; (f n)
; (A 0 n)
; (* 2 n)
; so f(n) = 2n

; (g n)
; (A 1 n)

; (A (- 1 1)
;     (A 1 (- n 1)))

; (A 0
;     (A 1 (- n 1)))

; (* 2 (A 1 (- n 1)))

; (* 2 
;     (A (- 1 1)
;         (A 1 (- (- n 1) 1)))
; )

; (* 2 
;     (A 0
;         (A 1 (- (- n 1) 1)))
; )

; (* 2 
;     (* 2
;         (A 1 (- (- n 1) 1)))
; )

; (* 2 
;     (* 2
;         (* 2
;             (A 1 (- (- (- n 1) 1) 1))))
; )

; and so on
; suppose n = 4
; (* 2 
;     (* 2
;         (* 2
;             (A 1 1)))
; )

; (* 2 
;     (* 2
;         (* 2
;             2))
; )
; so it equals 2^4
; so, g(n) = 2^n

(define n 3)
(h n)
(A 2 n)

(A (- 2 1)
    (A 2 (- n 1)))

(A 1
   (A 2 (- n 1)))

(g (A 2 (- n 1)))

(g (A (- 2 1)
   (A 2 (- (- n 1) 1))))

(g 
  (g
    (A 2 (- (- n 1) 1))))
; let n = 3

(g 
  (g
    (A 2 1)))
(g 
  (g
    2))
; = 2^2^2
; g(n) = 2^2 exponent done n times total
; g(n) = 2↑↑n


; (g 
;   (g
;    (A (- 2 1)
;       (A 2 (- (- (- n 1) 1) 1)))))

; (g 
;   (g
;    (g
;       (A 2 (- (- (- n 1) 1) 1)))))

; throw away below

; (A 1
;     (A (- 2 1)
;        (A 2 (- (- n 1) 1))))



; let n = 3
; (A 1
;     (A 1
;        2))

; (A 1
;     (A 0
;        (A 1 1)))

; (A 1
;     (* 2 2))

; (A (- 1 1)
;    (A 1 (- (* 2 2) 1)))


; (* 2
;    (A 1 (- (* 2 2) 1)))

; (* 2
;    (A (- 1 1)
;       (A 1 (- (- (* 2 2) 1) 1))))

; (* 2
;    (* 2
;       (A 1 (- (- (* 2 2) 1) 1))))

; (* 2
;    (* 2
;       (A (- 1 1)
;          (A 1 (- (- (- (* 2 2) 1) 1) 1)))))

; (* 2
;    (* 2
;       (* 2
;          (A 1 (- (- (- (* 2 2) 1) 1) 1)))))

; (* 2
;    (* 2
;       (* 2
;          (A 1 1))))

; (* 2
;    (* 2
;       (* 2
;          2)))